### ISSUE TITLE
posenet.py with RTSP as input not display image 

### ISSUE THREAD

**Issue by AnhDai1997** [dusty-nv/jetson-inference#1375]
Hi! I want to show image as output with input from RTSP by this command (on jetson xavier NX):
posenet.py --network=Pose-ResNet18-Body \<my RTSP link\> display://0
Code run  normally but not show image

**Comment by dusty-nv** [comment]
Hi @AnhDai1997, hmm - can you try modifying the [posenet.py](https://github.com/dusty-nv/jetson-inference/blob/master/python/examples/posenet.py) script so that it creates the `videoOutput` object before the `poseNet` object (similar to how [`detectnet.py`](https://github.com/dusty-nv/jetson-inference/blob/master/python/examples/detectnet.py) does it)

After you modify posenet.py, remember to rerun `cmake ../` and `sudo make install` from your build directory so that your updated script gets installed.
