### ISSUE TITLE
How to modify the pre processing and post processing to use different networks on the jetson-inference

### ISSUE THREAD

**Issue by zmhcasmy** [dusty-nv/jetson-inference#1507]
Hello,I I have realized running real-time object detection (ssd mobile) on Jetson through your github.I'm not very clear about the underlying logic, so I'm just giving my opinion. In this code "python3 train_ssd. py -- dataset type=voc -- data=data/<YOUR-DATASET>-- model dir=models/<YOUR-MODEL>", "ssd-mobilenet-v1. pth" is called through "train_ssd. py" to train my own dataset. After training, "onnx_export. py" is used to convert the PyTorch model to ONNX.Howerver, I think only a SSD-mobilenet  is not enough to deal with different applications,so  I want to try to use other object detection networks on it .
I have tried to find the answer to this question in your github's Issues module.And I see a problem that may be similar.
Here is a link to this question--"https://github.com/dusty-nv/jetson-inference/issues/1151".I also know that the pre-processing and post-processing of different models are different, but I don't know how to code all required logic .I wonder if you can provide a simple example to help me understand how to make preprocessing changes.Could you choose any object detection networks different from ssd-mobrienet, to try to explain?I think if your framework can adapt to different models, it will be a great blessing for us learners.Any reply will be given with the highest respect.Thank you for your help.

**Comment by dusty-nv** [comment]
> Could you choose any object detection networks different from ssd-mobrienet, to try to explain?I think if your framework can adapt to different models, it will be a great blessing for us learners

The first requirement for a different network, is that the network is able to be exported to ONNX, and that ONNX can be imported into TensorRT.   You can quickly check that TensorRT can load the ONNX with the `trtexec` tool.

I don't have tutorials about modifying the jetson-inference internals to support different models, because it is a lot of open-ended support.  However the pre/post-processing code is here that you may need to adapt:

* https://github.com/dusty-nv/jetson-inference/blob/c7ca374dbaa1417fbdb5fe0836d5ae843d7365eb/c/detectNet.cpp#L541
* https://github.com/dusty-nv/jetson-inference/blob/c7ca374dbaa1417fbdb5fe0836d5ae843d7365eb/c/detectNet.cpp#L601

**Comment by zmhcasmy** [comment]
Thank you for your patient and detailed answer. Do you mean that I can use detectnet for object detection tasks as long as I have a network that can be exported as ONNX and this ONNX file can be imported into tensorRT, and then I can use detectnet after following your tips?
I exported the yolov5.onnx file on windows, do I just need to apply your changes and then I can run it on jetson? Or do I need to change something more.
