### ISSUE TITLE
Process killed by segmentation fault (detection)

### ISSUE THREAD

**Issue by SaTz1483** [dusty-nv/jetson-inference#1571]
Hey @dusty-nv
Could you please help me out here ?

I'm actually trying to train a custom dataset on the detection algorithm given here using detectnet.

The images have a resolution of 4208x3120 inside which there are annotations made and its taking ridiculously long upto 3 steps for the 0th epoch . And the training abruptly crashes with this error 
Does resolution play a role here?

For reference 
![IMG_20230228_153638.jpg](https://user-images.githubusercontent.com/93349594/221822488-91827e46-1ed0-43df-9a6e-d4069b99b77a.jpg)

**Comment by dusty-nv** [comment]
Hi @SaTz1483, the images get downsampled to 300x300 for the DNN anyways, but yea it will take up more memory loading those 4K images.  You could try running it with `--workers=0` or `--workers=1` to see if that helps.  Also you could resize your images in your dataset somehow.  The issue is that the annotations will also need adjusted.
