### ISSUE TITLE
How can I train segmentation using FCN-Alexnet with 360p images?

### ISSUE THREAD

**Issue by teoac** [dusty-nv/jetson-inference#238]
I'm following the examples of segmentation.
I don't have enough memory on my graphic card, so I want to train with 360p images. (When I try training with 720p images, I always meet the 'out of memory' error.)
After training with 360p images, the results on the host PC are very good and similar to tutorials.
But when I test on the jetson TX2, the results are not good.
Is there any additional work to use on my jetson TX2 when I train using 360p images?

![output_0255](https://user-images.githubusercontent.com/34938592/40587515-e47525b6-620a-11e8-8a40-bcf65a1a4fba.png)
![output_0428](https://user-images.githubusercontent.com/34938592/40587530-14f908c4-620b-11e8-8d59-27c1927cf4ad.png)
#

**Comment by bpinaya** [comment]
What graphics card do you have? Are you using batches greater than 1? Maybe that's the issue. You shouldn't have problems to train with 720p

**Comment by teoac** [comment]
@bpinaya Thank you for your reply. My graphics card is GTX 1060Ti w/ 3GB RAM. I cannot sure what batch size was set, but the size was larger than one.
As I said, the test result is very good on my host PC. But the test result on Jetson TX2 is poor as you can see above. I cannot understand why the result is not the same even if I used the same deep learning model.

**Comment by bpinaya** [comment]
Uhm... don't worry, let's try to figure it out? What command are you using to deploy the network in the TX2? Maybe you are choosing a different network. also there will be some low resolution since Dustin is not using the deconvolution layer and just doing bilinear interpolation, even though the results should look better. From what I can see in your image it seems that the results are shifted since the slope seems to be the same.
