### ISSUE TITLE
Deconvolution not working at image segmentation 

### ISSUE THREAD

**Issue by serdarozerr** [dusty-nv/jetson-inference#248]
I followed Image "Segmentation with SegNet" at this page. End of the page dustin  said that some layers like deconvolution and crop layers don't supported with this TensorRT version so delete this layer. I used jetson TX2 and running inside TensorRT 3.0.4 . According to TensorRT 3.0.1 release notes, now it is supporting deconvolution layers and also some restrictions are lifted. So I used deconvolution layer to get same size or close size output image as like input image. But deconvolution layer not working at all. Lets say I have  pixel size of 576 * 720 image. After convolution layers image size decreasing to 19*23. Then i applied 1 deconvolution layer with kernel size 63 and stride 32 but, i got same image size before deconvoltion applied which is 19 * 23 pixel size. 

Any answers, tips is greatly appreciated.

**Comment by bpinaya** [comment]
Hey there, are you sure you are getting a small output after the deconv layer?
If you check the network definition that Dustin is using for the inference, the output is the following:
![output1](https://user-images.githubusercontent.com/2473733/44198834-af8d8100-a142-11e8-95d3-a230c5e835c1.png)
Meaning that you have 58x21 pixels and 21 channels (the number of classes).

If you include the deconv (the 'upscore_21classes' layer) you should get an output of 2111x1087 and 21 channels, this is for a 2048x1024 image. So something like:
![output2](https://user-images.githubusercontent.com/2473733/44199015-41958980-a143-11e8-9f50-9d20286d6562.png)


What the code currently does is taking the 58x21 output and perform bilinear interpolation to get the segmentation mask.

Check again that you are allocating enough memory for the deconv layer.

**Comment by bpinaya** [comment]
Updating this, I've since then ran the deconv layer and indeed you get smoother segmentations like in this segmented inference:
![screenshot from 2018-08-17 14-34-20](https://user-images.githubusercontent.com/2473733/44340181-5300cd80-a484-11e8-9c3d-2dc5e9f885a5.png)

But indeed the times are horrible, just for the deconv layer it takes about 4 seconds on an Geforce1080Ti. At this point I think it might be an issue on implementation of the deconv layer.

Some people have complained already about the slow times on the deconv [here](https://devtalk.nvidia.com/default/topic/1036168/tensorrt/deconvolution-layer-runs-super-slow-in-tensorrt/)
and [here](https://devtalk.nvidia.com/default/topic/1036168/tensorrt/deconvolution-layer-runs-super-slow-in-tensorrt/). In the last link  they've already acknowledged it is a bug reproducible in TensorRT4.1 so probable there will be a fix in the future.
