### ISSUE TITLE
I identify a picture and need 3 seconds.How can i  decrease time.

### ISSUE THREAD

**Issue by MarkandWen** [dusty-nv/jetson-inference#264]
Hi,I used ./imagenet-console 1.jpg 2.jpg command to identifya picture and need 3 seconds.And i found that i need 2.8 seconds between networks XX loaded and CUDA engine context initialized with 2 bindings.How can decrease time within one second.Please help us check it,thanks.

**Comment by dusty-nv** [comment]
Hi @MarkandWen, I recommend that you fork `imagenet-camera` program with your own daemon, that already has the network loaded and waiting to receive new images to process.  The existing `imagenet-camera` is a simple example that processes a single image from disk and then exits.  You could modify it to process multiple images or wait to receive new images.  This would greatly reduce the start-up time since the network only needs to be loaded once at the initialization of the program.
