### ISSUE TITLE
camera.CaptureRGBA() hangs

### ISSUE THREAD

**Issue by BouweCeunen** [dusty-nv/jetson-inference#434]
The `img, width, height = camera.CaptureRGBA()` function just hangs after approximately 30minutes of running. I already configured the timeout option to 0, so that it immediately returns when no frame is available. Anyone any idea? Thanks.

**Comment by ledaiduongvnth** [comment]
I have the same issue. Please help!

**Comment by ledaiduongvnth** [comment]
It seems the timeout does not work

**Comment by dusty-nv** [comment]
Can you try using the videoSource interface?   see here for example:  

* https://github.com/dusty-nv/jetson-utils/blob/916023814a1ac1401380c5d4313454c78c0a5f40/python/examples/video-viewer.py
* https://github.com/dusty-nv/jetson-inference/blob/master/docs/aux-streaming.md

Also, what happens if you try a timeout like `timeout=100`?
