### ISSUE TITLE
how to set "mCoverageThreshold" and "threshold"

### ISSUE THREAD

**Issue by ShervinAr** [dusty-nv/jetson-inference#52]
Dear all, could you please let me know how the Digits environment set the "mCoverageThreshold" and "threshold" parameters used in DetectNet?

**Comment by abdo-abaco** [comment]
on detectnet-camera.cpp instead of calling:

net = detectNet::Create(networkType);

call this:

net = detectNet::Create(networkType, 0.5, 10);

I have been messing around with this in an attempt to get the exact output shown on this projects main page : ./detectnet-console peds-008.png output_8.png multiped
