### ISSUE TITLE
Deconvolution groups

### ISSUE THREAD

**Issue by lbin** [dusty-nv/jetson-inference#56]
Hi @dusty-nv 
In gie's doc said, it doesnot supprot Deconvolution groups, pls give me some reference about what is this layer.
Thanks.

**Comment by dusty-nv** [comment]
Hi Li,

Is this pertaining to FCN-Alexnet?  The deconv groups should be removed to get it to load with TensorRT.   Actually I remove the whole deconv layer, because it has learning rate = zero (i.e. is a simple linear upscaling) and is pretty slow.

Hope that helps,
Dustin


-------- Original message --------

**Comment by lbin** [comment]
Thanks for you reply, dusty!
My model has some different with FCN_Alexnet, so I must use deconv layer. I could load my model with deconv layer in TensorRT, but I got error results from this layer.  My deconv layer doesnot have `group` param, so what is `deconv groups`?
