### ISSUE TITLE
Output render cudaFromNumpy

### ISSUE THREAD

**Issue by jinmingteo** [dusty-nv/jetson-inference#726]
Hi, thanks for the awesome work. I would like to ask about the output rendering function.

1) Is output rendering faster compared to cv2.imshow? 

2) How do i convert a cv2 image to render using output.render or display.render?

Things that I have tried:

```
        display = jetson.utils.glDisplay()

 	show_frame = cv2.cvtColor(show_frame, cv2.COLOR_BGR2RGBA)

	height, width, channels = show_frame.shape

	display_img = jetson.utils.cudaFromNumpy(show_frame)

	# # render the image
	display.RenderOnce(display_img, width, height)
```

```
        output = jetson.utils.videoOutput(opt.output_URI, argv=sys.argv+is_headless)

 	show_frame = cv2.cvtColor(show_frame, cv2.COLOR_BGR2RGBA)

	height, width, channels = show_frame.shape

	display_img = jetson.utils.cudaFromNumpy(show_frame)
        
	output.Render(display_img)
```

Thanks in advance!

**Comment by dusty-nv** [comment]
> 1. Is output rendering faster compared to cv2.imshow?

Normally the OpenGL-based videoOutput interface would be faster, because it is optimized for CUDA->OpenGL interoperability, but if the image is already in cv2 format (numpy array), then it may be faster to just use `cv2.imshow()`.


> 2\. How do i convert a cv2 image to render using output.render or display.render?
You can see the `cuda-from-cv.py` sample here:   https://github.com/dusty-nv/jetson-utils/blob/master/python/examples/cuda-from-cv.py

Note that there is also a `cuda-to-cv.py` sample as well.
