### ISSUE TITLE
Building the Project from Source Cmake Issue

### ISSUE THREAD

**Issue by ianrheewhi** [dusty-nv/jetson-inference#758]
So I've been working on getting through the setup, but I
I'm building the project from source rather than using the Docker.
When I try to install PyTorch or cmake ../, I get the following issue: 

`CMake Error: The following variables are used in this project, but they are set to NOTFOUND.`
`Please set them or make sure they are set and tested correctly in the CMake files:`
`CUDA_CUDART_LIBRARY (ADVANCED)`
    `linked by target "jetson-inference" in directory /home/jsh/jetson-inference`
    `repeating message`
`CUDA_TOOLKIT_INCLUDE (ADVANCED)`
   `used as include directory in directory /home/jsh/jetson-inference`
   `repeating message`

`-- Configuring incomplete, errors occurred!`
`See also "/home/jsh/jetson-inference/build/CMakeFiles/CMakeOutput.log".`

I've deleted the project folder and tried to do it again, but the issue persists. I've followed the instructions to a T,
I  don't know what I'm doing wrong; I've been trying to debug for hours. I would appreciate any and all input.

**Comment by dusty-nv** [comment]
Hi @ianrheewhi , can you check that you have the CUDA toolkit installed on your Jetson?

You should be able to find it under `/usr/local/cuda`

If you don't have CUDA, you would need to install it.   I'm not sure which Jetson you are using or version of JetPack, but if you are on JetPack 4.3 or newer you should be able to run `sudo apt-get install nvidia-jetpack`.   Otherwise, you could use SDK Manager tool to install it or if you are on Nano/Xavier-NX you can flash the NVIDIA SD card image.

**Comment by DennisFaucher** [comment]
@dusty-nv thanks for this. I just re-images my Xavier with the SDK Manager and nvidia-jetpack was not installed. I will install and see if my cmake errors go away.
