### ISSUE TITLE
Transmitting output stream in RTSP or HTTP

### ISSUE THREAD

**Issue by mmatesic01** [dusty-nv/jetson-inference#798]
Hello,

As documentation explains only RTP transmittingg is possible. 
(https://github.com/dusty-nv/jetson-inference/blob/master/docs/aux-streaming.md#rtp)
And it works fine using VLC player.

But at my end point (https://www.home-assistant.io/integrations/generic) I am able to capture/grab only from RTSP or HTTP streams.
Are there any plans to make such broadcasting or do you have any advice here how to implement existing RTP stream?

Thank you.

**Comment by dusty-nv** [comment]
You might want to try for some external program that can convert RTP -> RTSP.  Otherwise, I'm afraid I don't have a simple solution.   GStreamer doesn't include RTSP server support by default, that is only included in another library found here:

https://github.com/GStreamer/gst-rtsp-server

I'm not sure if maybe that could be used to convert RTP -> RTSP.   Maybe you could install that gst-rtsp-server, and run a pipeline on it that got the RTP stream and served RTSP instead.

I haven't planned integrating this gst-rtsp-server with jetson-inference itself, because it appears pretty complex to use programatically.   But perhaps you could modify one of the samples that comes with gst-rtsp-server to accomplish what you desire.
