### ISSUE TITLE
I want to know the difference between nvidia tlt and jetson-inference

### ISSUE THREAD

**Issue by ingbeeedd** [dusty-nv/jetson-inference#848]
What is the difference between Nvidia TLT platform and this program(jetson-inference) in terms of training? I think it's the same process. I'm curious.

**Comment by WaldoPepper** [comment]
I think TLT is closely linked to Deepstream, especially regarding how you do inference. The TLT approch is different, because you control the process completely by configuration files. You have a wide range of nets to choose from (incl. YOLO, etc.) but I would consider it less "open".

I presume it will use the same PyTorch bindings at the end....
