### ISSUE TITLE
Getting camera window size

### ISSUE THREAD

**Issue by mhammaddaoud** [dusty-nv/jetson-inference#966]
Hello,
When i run detectnet object detection, a window pops up displaying the camera with the detections boxes
How can i get the width and height of the display through python code?
Thank you.

**Comment by dusty-nv** [comment]
Hi @mhammaddaoud, it should basically be the same as the camera's image width/height

**Comment by mhammaddaoud** [comment]
Its changing according to the screen size

**Comment by dusty-nv** [comment]
So the display takes up pretty much the whole screen?   It should match the camera image.

Do you want the dimensions of the screen or the window?  If you want the window dimensions, you will need to create a glDisplay object instead of videoSource, and then call `.GetWidth()` and `.GetHeight()` on it.  Here is older version of detectNet using glDisplay:

https://github.com/dusty-nv/jetson-inference/blob/20200714/python/examples/detectnet-camera.py
